#!/bin/sh

set -e

case "${1}" in
	configure)
		adduser \
			--system \
			--home /var/lib/rafka \
			--no-create-home \
			--quiet \
			--group \
			rafka || true
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#
